### ISSUE TITLE
Stopped working since iOS 11.4

### ISSUE THREAD

**Issue by fungilation** [aschaper/homebridge-sesame#1]
Not sure if it's this plugin or `homebridge`: https://github.com/nfarina/homebridge/issues/1876

**Comment by sleepyarmistice** [comment]
I’ve got the same problem, but all my other homebridge stuff is still working.

**Comment by fungilation** [comment]
Really. I tried homebridge-qsesame and homebridge-sesame-beta, none works with homebridge for me. Says accessory can't be found on adding homebridge's QR code

**Comment by aschzero** [comment]
Hello! I'm not sure what could be causing these issues and I haven't had any problems with iOS 11.4. Are there any errors being logged to your homebridge log file?

Also, are you able to use Homebridge with other accessories? I'm curious because it sounds like the issue is related to your Homebridge installation since you mentioned this happens when trying to add Homebridge with the QR code. It's a bit misleading, but the accessory in the "Accessory can't be found" message is actually referring to the bridge that gets created when adding Homebridge which is itself considered an accessory in HomeKit.

One way you can verify this would be to start fresh and try to add Homebridge with no accessories. You would have to clear out your homebridge config file and remove the following directories: `persist`, `accessories`, and `node_modules`. If you restart homebridge and you get the same behavior, that's a good indicator that something could be wrong with your homebridge installation or with your home network.

**Comment by sleepyarmistice** [comment]
My homebridge installation has continued to work normally with the exception of sesame. When homebridge starts up, I get this error: 

[2018-6-5 19:40:36] [Sesame] Encountered an error when trying to get locks: StatusCodeError: 400 - {}

**Comment by aschzero** [comment]
Hi @sleepyarmistice thanks for the report, I've noticed that happening as well and it is apparently a known issue with the API: https://community.candyhouse.co/t/v1-sesames-endpoint-returning-400-bad-request-but-others-still-work/1265 Really hoping it gets fixed soon.

Edit: thread moved to https://github.com/aschaper/homebridge-sesame/issues/2
